app.use((_,res,next)=>{
    //  res.status(404).send(`<h1>Samething is Wrong! </h1>`)
    const error = new Error ("<h1>Samething went Wrong! </h1>");
    error.status = 404;
    next(error)
});

app.use((error,req,res,next) => {
    console.log('Error', error);
    
    if(error.status){
        return res.status(error.status).send(`<h1>${error.message}</h1>`)
    }

    res.status(500).send("<h1>This is Server Error!</h1>")
})
